// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6KVAvzWElABA0eVHTMbYllRbvhrdwn6o',
    appId: '1:371474641591:web:17b441341df809a4911332',
    messagingSenderId: '371474641591',
    projectId: 'android19m',
    authDomain: 'android19m.firebaseapp.com',
    databaseURL: 'https://android19m-default-rtdb.firebaseio.com',
    storageBucket: 'android19m.firebasestorage.app',
    measurementId: 'G-MP2M8V0WDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMUHBUGRbdbOE-1WS27_Vqz3uWssf3q0',
    appId: '1:371474641591:android:3e79ca0e455e43c1911332',
    messagingSenderId: '371474641591',
    projectId: 'android19m',
    databaseURL: 'https://android19m-default-rtdb.firebaseio.com',
    storageBucket: 'android19m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqtbcgCycNb1QfV-DWSKaBj7KE8nZMBE',
    appId: '1:371474641591:ios:af096add71ba6eb9911332',
    messagingSenderId: '371474641591',
    projectId: 'android19m',
    databaseURL: 'https://android19m-default-rtdb.firebaseio.com',
    storageBucket: 'android19m.firebasestorage.app',
    iosClientId: '371474641591-4bt9cfv3fj8dg73s408f2ktht058gdcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillbridg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqtbcgCycNb1QfV-DWSKaBj7KE8nZMBE',
    appId: '1:371474641591:ios:af096add71ba6eb9911332',
    messagingSenderId: '371474641591',
    projectId: 'android19m',
    databaseURL: 'https://android19m-default-rtdb.firebaseio.com',
    storageBucket: 'android19m.firebasestorage.app',
    iosClientId: '371474641591-4bt9cfv3fj8dg73s408f2ktht058gdcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillbridg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6KVAvzWElABA0eVHTMbYllRbvhrdwn6o',
    appId: '1:371474641591:web:4bf28d8668b161a8911332',
    messagingSenderId: '371474641591',
    projectId: 'android19m',
    authDomain: 'android19m.firebaseapp.com',
    databaseURL: 'https://android19m-default-rtdb.firebaseio.com',
    storageBucket: 'android19m.firebasestorage.app',
    measurementId: 'G-NHS9C5QJLT',
  );
}
